<a href="https://colab.research.google.com/github/CastanedaZUlises/practica_3/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import matplotlib.pyplot as plt
from pylab import mpl
import numpy as np
import pandas as pd
import math

def newton_interpolation(X,Y,x):
    """
         Calcular la interpolación en x puntos
    """
    sum=Y[0]
    temp=np.zeros((len(X),len(X)))
         # Asignar la primera línea
    for i in range(0,len(X)):
        temp[i,0]=Y[i]
    temp_sum=1.0
    for i in range(1,len(X)):
                 #x polinomio
        temp_sum=temp_sum*(x-X[i-1])
                 # Calcular diferencia de medias
        for j in range(i,len(X)):
            temp[j,i]=(temp[j,i-1]-temp[j-1,i-1])/(X[j]-X[j-i])
        sum+=temp_sum*temp[i,i]
    return sum

In [14]:
import matplotlib.pyplot as plt
from pylab import mpl
import numpy as np
import pandas as pd
import math
def get_diff_table(X,Y):
    """
    Obtenga la tabla de interpolación
    """
    n=len(X)
    A=np.zeros([n,n])

    for i in range(0,n):
        A[i][0] = Y[i]

    for j in range(1,n):
        for i in range(j,n):
            A[i][j] = (A[i][j-1] - A[i-1][j-1])/(X[i]-X[i-j])

    return A

In [16]:
X=[-1,0,1,2,3,4,5]
Y=[-20,-12,1,15,4,21,41]
A = get_diff_table(X,Y)
df = pd.DataFrame(A)
df

      0     1     2         3         4         5         6
0 -20.0   0.0   0.0  0.000000  0.000000  0.000000  0.000000
1 -12.0   8.0   0.0  0.000000  0.000000  0.000000  0.000000
2   1.0  13.0   2.5  0.000000  0.000000  0.000000  0.000000
3  15.0  14.0   0.5 -0.666667  0.000000  0.000000  0.000000
4   4.0 -11.0 -12.5 -4.333333 -0.916667  0.000000  0.000000
5  21.0  17.0  14.0  8.833333  3.291667  0.841667  0.000000
6  41.0  20.0   1.5 -4.166667 -3.250000 -1.308333 -0.358333

In [22]:
xs=np.linspace(np.min(X),np.max(X),1000,endpoint=True)
ys=[]
for x in xs:
    ys.append(newton_interpolation(X,Y,x))

In [23]:
plt.title("newton_interpolation")
 plt.plot (X, Y, 's', label = "valores originales") #El punto azul representa el valor original
 plt.plot (xs, ys, 'r', label = 'valores de interpolación') # Curva de interpolación
plt.xlabel('x')
plt.ylabel('y')
 plt.legend (loc = 4) # Especifique la posición de la leyenda

IndentationError: ignored